# A sample Gemfile
source "https://rubygems.org"

gem 'puma'
gem 'actionmailer', '= 3.2.14'
gem 'activemodel', '= 3.2.14'
gem 'activerecord', '= 3.2.14'
gem 'activeresource', '= 3.2.14'
gem 'activesupport', '= 3.2.14'
gem 'haml', '= 4.0.3'
gem 'mysql2', '= 0.3.13'
gem "sinatra", "= 1.4.3"
gem 'sqlite3', '= 1.3.8'
gem 'sinatra-activerecord', '= 1.2.3'
gem 'rack', '= 1.4.5'
# rack-cache (1.2)
# rack-protection (1.5.0)
# rack-ssl (1.3.3)
# rack-test (0.6.2)
# rails (3.2.14)
# railties (3.2.14)
# rake (10.1.0)
# rdoc (3.12.2)
# rubygems-bundler (1.3.3)
# rvm (1.11.3.8)
# sinatra (1.4.3)
# sinatra-activerecord (1.2.3)
# sprockets (2.2.2)
# sqlite3 (1.3.8)
# thor (0.18.1)
# thread_safe (0.1.3)
# tilt (1.4.1)
# treetop (1.4.15)
# tzinfo (0.3.37)

# gem "actionpack"

# gem "haml"
# gem "json"
# # gem "activerecord", '~> 3.2.13'
# gem "sinatra-activerecord"
# gem "actionmailer"
# gem "logger"

